name: Terraform CI

on:
  pull_request:
    paths:
      - 'envs/**.tf'
      - 'modules/**.tf'

jobs:
  terraform-check:
    name: Terraform Format, Validate, Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Initialize Terraform
        run: |
          cd envs/staging
          terraform init -backend=false

      - name: Check Formatting
        run: |
          cd envs/staging
          terraform fmt -check

      - name: Validate Terraform
        run: |
          cd envs/staging
          terraform validate

      - name: Terraform Plan (no backend)
        run: |
          cd envs/staging
          terraform plan -input=false -var-file="terraform.tfvars"
